// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVd1tygdsdQ1RsceR-LULj28m4o_KhAmE',
    appId: '1:799765349068:web:a3794356bfe4798838f869',
    messagingSenderId: '799765349068',
    projectId: 'fit-track-app-104b3',
    authDomain: 'fit-track-app-104b3.firebaseapp.com',
    storageBucket: 'fit-track-app-104b3.appspot.com',
    measurementId: 'G-G1CBVD68N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfhcZdAQaNbRt36n5d1u7y906-RIdNjGM',
    appId: '1:799765349068:android:5f64e76f5158ad2e38f869',
    messagingSenderId: '799765349068',
    projectId: 'fit-track-app-104b3',
    storageBucket: 'fit-track-app-104b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg9PX30uJ4vOpEXCpzDjYrXQXEZ0UG9W8',
    appId: '1:799765349068:ios:32c4832b76fc5dfa38f869',
    messagingSenderId: '799765349068',
    projectId: 'fit-track-app-104b3',
    storageBucket: 'fit-track-app-104b3.appspot.com',
    iosBundleId: 'com.example.fitTrackApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg9PX30uJ4vOpEXCpzDjYrXQXEZ0UG9W8',
    appId: '1:799765349068:ios:32c4832b76fc5dfa38f869',
    messagingSenderId: '799765349068',
    projectId: 'fit-track-app-104b3',
    storageBucket: 'fit-track-app-104b3.appspot.com',
    iosBundleId: 'com.example.fitTrackApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVd1tygdsdQ1RsceR-LULj28m4o_KhAmE',
    appId: '1:799765349068:web:9378842daf340ba638f869',
    messagingSenderId: '799765349068',
    projectId: 'fit-track-app-104b3',
    authDomain: 'fit-track-app-104b3.firebaseapp.com',
    storageBucket: 'fit-track-app-104b3.appspot.com',
    measurementId: 'G-MGLT3158CL',
  );
}
